[tool.poetry]
name = "ukhaan-api"
version = "0.1.0"
description = "API Project of nepali-ukhaan-project"
authors = ["Aashish Chapain  <ashishchapain86@gmail.com>", "Sushil <NA>"]
readme = "README.md"
packages = [{include = "ukhaan_api"}]

[tool.poetry.dependencies]
python = "^3.10"
anyio = "3.6.2"
beautifulsoup4 = "4.11.2"
certifi = "2022.12.7"
charset-normalizer = "3.0.1"
click = "8.1.3"
colorama = "0.4.6"
fastapi = "0.92.0"
h11 = "0.14.0"
idna = "3.4"
markdown = "3.4.1"
pydantic = "1.10.5"
requests = "2.28.2"
sniffio = "1.3.0"
soupsieve = "2.4"
starlette = "0.25.0"
typing-extensions = "4.5.0"
urllib3 = "1.26.14"
uvicorn = "0.20.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
